# Generated by Django 2.0.1 on 2018-08-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('article_type', models.CharField(max_length=200)),
                ('article_subtype', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=500)),
                ('read', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('like', models.IntegerField()),
                ('collect', models.IntegerField()),
                ('content', models.TextField()),
                ('user_like', models.TextField()),
                ('user_collect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=200)),
                ('like', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('headUrl', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('user_like', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=1)),
                ('slogan', models.CharField(max_length=200)),
                ('banner_url', models.CharField(max_length=1000)),
                ('other_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
